### ISSUE TITLE
Cannot log into site after enabling ringcaptcha 

### ISSUE THREAD

**Issue by jameskenney** [moxi9/phpfox-sms-captcha#1]
I'm getting "Missing RingCaptcha access keys" error at login page. The app works though. I can set up a new account and a code is sent to my phone. The code works. But I'm taken back to the visitor login screen with the same error message. I'm locked out of my website.
# PHPfox_SMSCaptcha

**Comment by RaymondBenc** [comment]
I tried to reproduce this issue locally and wasn't able to. If you **uninstall** the app, can you login? If you cannot login in order to uninstall the app, you can manually install if from your web server via FTP/cPanel. Just navigate to the folder **PF.Site/Apps/PHPfox_SMSCaptcha** and rename the file **app.lock** to **app.lock.backup**.
